#!/usr/bin/perl -w
#
# Tim Hawes
# 20th November 2008
#
# Identify the type of linefeeds being used in a file

use strict;

my $crlf = 0;
my $cr = 0;
my $lf = 0;

while (<>) {
    if (/\r\n/) {
	$crlf += 1;
    } elsif (/\n/) {
	$cr += 1;
    } elsif (/\r/) {
	$lf += 1;
    }
}

if ($crlf and !$cr and !$lf) {
    print "CRLF\n";
} elsif (!$crlf and $cr and !$lf) {
    print "CR\n";
} elsif (!$crlf and !$cr and $lf) {
    print "LF\n";
} elsif (!$crlf and !$cr and !$lf) {
    print "None\n";
} else {
    print "Mixed (CRLF=$crlf CR=$cr LF=$lf)\n";
}
